version: "2"
services:
  app:
    build: .
    working_dir: /var/www
    volumes:
      - ./:/var/www/
    ports:
      - 8080:80
    environment:
      - XDEBUG_HOST=docker.for.mac.localhost

  mongodb:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - 27018:27017

  redis:
    image: redis:3.2.11
    container_name: queue-redis
    ports:
      - 6389:6379
